server:
  port: 30602

# spring 配置
spring:
  application:
    name: alinesno-infra-platform-trainer-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/dev_alinesno_infra_plat_trainer_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password:  adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: aip@local
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.plat.trainer.entity
  database:
    type: mysql
  index:
    prefix: alinesno_plat_trainer_idx_
  unique:
    prefix: alinesno_plat_trainer_uni_
